version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: ./docker/apache.dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/usr/local/apache2/htdocs
      - ./docker/apache/000-default.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./docker/apache/000-default-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
    links:
      - php
  php:
    build:
      context: ./
      dockerfile: ./docker/php.dockerfile
    volumes:
      - ./:/usr/local/apache2/htdocs
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/zzz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
    links:
      - database
  database:
    image: mariadb:10.1
    volumes:
      - ./:/var/www/html
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=retrobad"
      - "MYSQL_USER=retrobad"
      - "MYSQL_PASSWORD=!123_AbCxYz"
      - "MYSQL_ROOT_PASSWORD=crYpt1cP4$$"
  redis:
    image: redis:3.0
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  data:
